quarkus.http.port=8081


# authentication configs
quarkus.oidc.auth-server-url=http://localhost:8180/realms/quarkus
quarkus.oidc.client-id=backend-service
quarkus.oidc.credentials.secret=secret

#data source config
quarkus.datasource.db-kind= postgresql
quarkus.datasource.username= postgres
quarkus.datasource.password= Leao2004
quarkus.datasource.jdbc.url= jdbc:postgresql://localhost:5433/reportdb
quarkus.hibernate-orm.database.generation= update


# kafka configs - report
mp.messaging.incoming.proposal.connector = smallrye-kafka
mp.messaging.incoming.proposal.topic = proposal
mp.messaging.incoming.quotation.topic = quotation
mp.messaging.connector.smallrye-kafka.bootstrap.servers = localhost:9092
quarkus.log.category."io.smallrye.reactive.messaging.kafka".level=DEBUG
quarkus.devservices.enabled=false
quarkus.kafka.devservices.enabled=false

# open-tracing
quarkus.jaeger.service-name=reporte
quarkus.jaeger.sampler-type=const
quarkus.jaeger.sampler-param=1
quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n